name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn
          yarn test
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test
          output: comment
